---
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure support libraries are available
  package:
    name: "{{ letsencrypt_pkgs }}"
    state: present

# taken from https://letsencrypt.org/certificates/
- name: Ensure ca.cer is uploaded onto server
  copy:
      src: ca.cer
      dest: '{{ letsencrypt_path }}/ca.cer'

- include_tasks: letsencrypt.yml
  loop: '{{ letsencrypt_certificates }}'
    
